---
title: Detroit Design Department
timezone: UTC
collections:
  designers:
    title: Designers
    output: true
  jobs:
    title: Jobs
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mark@waymark.com
description: Designers in Detroit.
baseurl: "/"
url: ''
twitter_username: _mrko_polo
github_username: mwbennett
header_pages:
- jobs.md
- post-job.md
- join.md
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
